trigger:
  tags:
    include:
      - 'v*'   # 例: v1.2.3 を push したときだけ動かす

pr: none

stages:
- stage: build_and_release_win
  displayName: Build (Windows) & Create GitHub Release
  jobs:
  - job: win
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: NodeTool@0
        inputs: { versionSpec: '18.x' }
      - script: |
          displayName: 'Build with electron-builder (win + zip)'
          npm ci
          npx electron-packager . live3ddice --platform=win32 --arch=x64 --icon=icon.ico --overwrite
          npx bestzip "live3ddice-win32-x64-$((cat .\package.json | ConvertFrom-Json).version).zip" .\live3ddice-win32-x64
      # dist/*.zip などを GitHub Release に添付
      - task: GitHubRelease@1
        displayName: 'Create GitHub Release + upload assets'
        inputs:
          gitHubConnection: 'github.com_sakkuntyo'   # Project settings > Service connections で作成
          repositoryName: 'sakkuntyo/electron-live3ddice'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'manual'
          tag: '$(Build.SourceBranchName)'                  # 例: v1.2.3
          title: '$(Build.SourceBranchName)'
          assets: './*.zip'
          isDraft: false
          isPreRelease: false
          addChangeLog: true
