trigger:
  tags:
    include:
      - 'v*'   # 例: v1.2.3 を push したときだけ動かす

pr: none

stages:
- stage: build_and_release_win
  displayName: Build (Windows) & Create GitHub Release
  jobs:
  - job: win
    pool:
      name: Default
      demands:
        - 'Agent.Name -equals ubuntu22-devops-selfhostagent'
    steps:
      - task: NodeTool@0
        inputs: { versionSpec: '18.x' }
      - script: |

          # 念のためのユーティリティ（なければ入れる）
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y jq
          fi

          # Windowsターゲットも作るなら wine を入れる（不要なら丸ごと削除OK）
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine64 wine32
          npm ci
          npx electron-packager . live3ddice --platform=win32 --arch=x64 --icon=icon.ico --overwrite
          npx bestzip "live3ddice-win32-x64-$((cat .\package.json | ConvertFrom-Json).version).zip" .\live3ddice-win32-x64
        displayName: 'Build with electron-builder (win + zip)'
      # dist/*.zip などを GitHub Release に添付
      - task: GitHubRelease@1
        displayName: 'Create GitHub Release + upload assets'
        inputs:
          gitHubConnection: 'github.com_sakkuntyo'   # Project settings > Service connections で作成
          repositoryName: 'sakkuntyo/electron-live3ddice'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'manual'
          tag: '$(Build.SourceBranchName)'                  # 例: v1.2.3
          title: '$(Build.SourceBranchName)'
          assets: './*.zip'
          isDraft: false
          isPreRelease: false
          addChangeLog: true
